export enum TransferStatus {
  PENDINGPAID = 'PENDINGPAID',
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  IN_PROGRESS = 'IN_PROGRESS',
  REQUEST_FINISH = 'REQUEST_FINISH',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
